### ISSUE TITLE
Progress Display

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#12]
Show progress in the terminal window.

I know how to do this (and I have already built modules to do so). I just need a 'percent' progress report throughout the generation code, and I should be able to hook in the rest.

As a side note, if you could start dropping some inline comments as you work (especially in the generation code), that would be great, as I feel lost in that area right now.

**Comment by ekaj2** [comment]
This would probably be better to wait on until we get more cleanup for the generation.

**Comment by MaximeHerpin** [comment]
Ok, I will comment the code. I am also reading some tutorials on how to use github properly.

**Comment by ekaj2** [comment]
I just read this (and I was using a workflow similar to the resolving conflicts page earlier) if you want to see it...it cleared a few things up for me:

http://dont-be-afraid-to-commit.readthedocs.io/en/latest/git/index.html

**Comment by ekaj2** [comment]
So after doing some tests with performance, I think that since most of the wait time is due to one nasty, horrid, terrible line of code:

`bpy.ops.uv.unwrap(method='ANGLE_BASED', margin=0.001)`

The best thing to do would be to just drop a few printouts to show what stage its at. Maybe: 

`"generating tree", "configuring particle system", "unwrapping", "adding armature", etc.`

**Comment by MaximeHerpin** [comment]
That's a great idea !

**Comment by ekaj2** [comment]
Added in progress branch!
