### ISSUE TITLE
Update Tree Armature Bug

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#14]
If you create a tree, then hit update, it keeps the old armature around :(

Please fix this on the release-1.0 branch and then make a pull request for merging it into develop. I will review both pull requests (merging the release into master and develop) and merge them. I would also like to do some more testing before merging the release into master. I'll let you know before merging into master, so you can pump the first "major release" on blender artists.

A super cool thing about the git branching model is that an end user can come along and download master whenever they want, and they will get the latest "stable" version.

**Comment by ekaj2** [comment]
What happened with this? I am seeing that all the release commits were reverted?

**Comment by MaximeHerpin** [comment]
My commit was registered on my computer, but didn't show online, so I reverted it and then reverted the revert to see if it would update, I ultimately pasted the code directly on github.

**Comment by ekaj2** [comment]
Don't know if you tried this or not...

Look at remotes
*git remote -v*
Find the name of the one linked to your repo...
*git push namefoundabove release-1.0*
