### ISSUE TITLE
Move UI to Separate Panels for Organization

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#2]
I feel like this would feel cleaner and easier to use if the settings were moved to separate panels so that they could be easily collapsed. For a panel, along with the other blender settings, you can set _bl_options = {'DEFAULT_CLOSED'}_ for not as important ones and users can open them to see the "advanced" stuff.

I feel like this would be good for you to do because I am not too familiar with this yet, and you can really rethink organization. However, if you feel the current ui boxes organize things pretty well, I can setup the panels with the boxes as the categories, and you can refine them later. Just assign someone to this or close it so I know what's up.

**Comment by MaximeHerpin** [comment]
You're right, it will give some room for more advanced controls. I will do it tomorrow morning.
When you say that the bl_info needs to be updated, you mean the blender version ? Or you don't want me to mention you as a writer ?

**Comment by ekaj2** [comment]
The location of the addon is no longer "View3D > Add > Mesh > Tree"

**Comment by ekaj2** [comment]
The bl_info update got bundled with the preset system...will work the panels soon.

**Comment by ekaj2** [comment]
Panels added in ui_update branch. New pull request for merging ui_update into develop.

**Comment by ekaj2** [comment]
Merged into develop.
