### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#3]
Could really use some presets...

Should be able to save all settings to a file for future reference and get them back based on an enum. I've something similar to this before so I think I'll give it an initial shot at least.

**Comment by MaximeHerpin** [comment]
It you could do it that would be great, it would give me the opportunity to learn from an example.

**Comment by ekaj2** [comment]
Can you "assign" me to it and label these two issues as enhancements?

**Comment by MaximeHerpin** [comment]
When I click on the Assignees button, only my name shows up.

**Comment by ekaj2** [comment]
Ok, that's fine...I can't do it from my end so I thought it would have to be the repo owner.

**Comment by ekaj2** [comment]
I think this may help:
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by MaximeHerpin** [comment]
No, I was reading the same thing, your name doesn't appears.

**Comment by ekaj2** [comment]
I forgot about delete functionality...will work on that later.

**Comment by ekaj2** [comment]
Added delete functionality.
