### ISSUE TITLE
"Make twig" button

### ISSUE THREAD

**Issue by MaximeHerpin** [MaximeHerpin/Blender-Modular-tree-addon#38]
It would be great to have a button to make a simple twig with leaves. I think twigs work much better than simple leaves when used as particles.

**Comment by ekaj2** [comment]
Are you finished with the twigs?

**Comment by MaximeHerpin** [comment]
Not yet, I will make a commit soon.

**Comment by ekaj2** [comment]
Working on adding into presets...

**Comment by ekaj2** [comment]
Finished adding to presets!

**Comment by ekaj2** [comment]
I must say I absolutely LOVE the new twig update! I've not done any renders yet to try it out, but it looks awesome in the viewport for sure! Excellent job.
