### ISSUE TITLE
Create twig with the new unwrap improvement

### ISSUE THREAD

**Issue by MaximeHerpin** [MaximeHerpin/Blender-Modular-tree-addon#55]
There is something wrong with the line "ind = '{0[0]:.5} {0[1]:.5} {1}'.format(loop[self.uvlayer].uv, loop.vert.index)" When the Make Twig operator is called

**Comment by ekaj2** [comment]
Are you using the change I just committed?

**Comment by MaximeHerpin** [comment]
Yes. I don't know why it does that.

**Comment by ekaj2** [comment]
What do you mean by "there is something wrong"?

**Comment by MaximeHerpin** [comment]
I get the error : "BMElem[key]: invalid key, must be a BMLayerItem"

**Comment by ekaj2** [comment]
So you *are* using the latest version from develop (you have already done a *git fetch*) and what are your twig settings? If you'd like, you can just make a preset and post the entire preset file here : )

**Comment by MaximeHerpin** [comment]
I am indeed using the latest version
My settings are the default ones: 1; 0.5; 678; 9

**Comment by MaximeHerpin** [comment]
Ok it works when I install the addon, I only get the error if I execute it as a script.

**Comment by ekaj2** [comment]
Awesome...are you using the version of the script-watcher addon that I posted [here](https://github.com/MaximeHerpin/Blender-Modular-tree-addon/issues/28)?

**Comment by MaximeHerpin** [comment]
Yep, I was just testing on another computer.
