### ISSUE TITLE
Built-in Presets

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#57]
Some presets would also help to understand the different parameters and be like a starting tutorial to learn from.

**Comment by ekaj2** [comment]
This could get ugly without a zip addon :(

I would prefer a separate package of .mtp files that a user could install.

**Comment by ekaj2** [comment]
I will work on the installer for now and some template presets...

**Comment by MaximeHerpin** [comment]
Wouldn't it be simpler to put them in the script ?

**Comment by ekaj2** [comment]
Simpler, yes, but cumbersome and not easily created/shared by non-coders.

**Comment by ekaj2** [comment]
Done with my part...can you add some more and edit the blank I made in the presets folder sometime?

**Comment by ekaj2** [comment]
Piece of cake to add built-in presets now (with zip add-on structure)! Have fun with it.
