### ISSUE TITLE
Batch tree creation

### ISSUE THREAD

**Issue by MaximeHerpin** [MaximeHerpin/Blender-Modular-tree-addon#62]
Just makes n trees on a grid with a seed variation.

**Comment by ekaj2** [comment]
Awesome, idea! Perhaps add a random scale to apply at the end?

**Comment by MaximeHerpin** [comment]
Or random radius, the scale randomness is taken care of by the particle settings. What do you think ?

**Comment by ekaj2** [comment]
Radius sounds fine. What do you mean "scale randomness is taken care of by particle settings"?

**Comment by MaximeHerpin** [comment]
If one wants to have multiple trees, it's probably to use them as a group for a particle system, and in such systems there is already an option to randomize the scale.

**Comment by ekaj2** [comment]
I see. Sounds good! BTW have you already seen the posts on the new BA thread? Do you mind linking to the wiki's installation guide instead of the .py file itself in the first post?

**Comment by MaximeHerpin** [comment]
Done :)

**Comment by ekaj2** [comment]
Is the batch tree operator done? Ready to add to presets?

**Comment by MaximeHerpin** [comment]
I think it is.

**Comment by ekaj2** [comment]
I fixed a couple bugs and did some cleanup...OK to merge?

**Comment by MaximeHerpin** [comment]
Yes :)
