### ISSUE TITLE
Moving Add-On to a Zip Format : |

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#73]
I would like to discuss this a bit to see if you are interested. Please let me know what you think.

Pros:

- Cleaner, easier to debug/manage
- Easy to add built-in presets
- Easy to add built-in twig models ([like how The Grove does twigs](https://www.thegrove3d.com/twigs/))
- Better for users
- I have made a zip add-on reloader to help with update time

Cons:

- Slower to update add-on in Blender for testing (Blender must be restarted on every update)

**Comment by MaximeHerpin** [comment]
It seems great :)

**Comment by ekaj2** [comment]
Are you working on any part of the add-on right now? I am expecting a **big** merge conflict if there are any changes other than moving it to a zip...this is a huge change!

**Comment by MaximeHerpin** [comment]
No, go on :)

**Comment by ekaj2** [comment]
I am basically done moving to modules...just wrapping up a few things.

**Comment by ekaj2** [comment]
Alright, pushed to github...

While this is by no means the *final* setup, I think it's a good start. Please rename your folder on your local repo to "modular_tree" instead of "Blender-Modular-tree-addon". Those dashes and the long name caused several problems. Also if you could change the github name (I don't know if that's possible), that'd be great as well.

**Comment by ekaj2** [comment]
I am working on pushing my zip add-on reloader to github so you can use that.

**Comment by ekaj2** [comment]
Ok...here is my addon reloader :-)

https://github.com/ekaj2/zip_addon_reloader/wiki
