### ISSUE TITLE
Replace armature system with displace modifier

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/Blender-Modular-tree-addon#76]
I am working on a new method of animating the trees with a displacement modifier instead of an armature. It looks promising, and will be much better suited for "sweeping wind" animations in a forest of trees. Removing the armature system will reduce the complexity of this add-on a lot and will speed up the creation process. What do you think? Should I remove the armature features entirely on this feature branch or just add this feature on top? I think this will make it **much** easier to animate.

**Comment by MaximeHerpin** [comment]
There are some issues with using displacement, but it's a good idea !
However,  armature can be useful to correct the aspect of a tree, so I don't think it should be removed from the addon. I have aleady some ideas to implement wind animation with the armature, but it would take a lot more time than a simple modifier (but would look more realistic perhaps). 

Anyway, It would be a very good thing to have two methods of simulating wind, one cheap (Modifier), and one exact but long (armature) :)

**Comment by ekaj2** [comment]
Alright, I'll leave armature in there for now. How's the zip format working for you?

**Comment by MaximeHerpin** [comment]
It is great !  Looks very professional

**Comment by ekaj2** [comment]
Done. Added a pull request.
